@echo off

rem This script was automatically generated by Leiningen.

setLocal

if "x%%JVM_OPTS%%" == "x" set JVM_OPTS=%%JAVA_OPTS%%
set CLASSPATH="%s"

java -cp "%%CLASSPATH%%" %%JVM_OPTS%% ^
 clojure.main -e "(use '%s)(apply -main *command-line-args*)" NUL %%*
