@echo off

rem This script was automatically generated by Leiningen.

setLocal

if "x%%JVM_OPTS%%" == "x" set JVM_OPTS=%%JAVA_OPTS%%
set CLASSPATH="%s"
set MAIN="%s"
set VERSION="%s"

java -cp "%%CLASSPATH%%" %%JVM_OPTS%% -Dproject.version=%%VERSION%%^
 clojure.main -e "(use '%%MAIN%%)(apply -main *command-line-args*)" NUL %%*
