;; This file is used to warn users when they attempt to load a plugin that
;; pulls in a dependency which conflicts with something already in use
;; by Leiningen itself.
{
 ;; Unhelpful to warn on these:
 ;; org.clojure/clojure "1.8.0"
 ;; leiningen-core "2.7.2-SNAPSHOT"
 bultitude "0.2.8"
 cheshire "5.6.3"
 clj-http "2.0.1"
 clj-stacktrace "0.2.7"
 clj-tuple "0.2.2"
 clojure-complete "0.2.4"
 com.cemerick/drawbridge "0.0.6"
 com.cemerick/pomegranate "0.3.1"
 com.fasterxml.jackson.core/jackson-core "2.7.5"
 com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.7.5"
 com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.7.5"
 com.hypirion/io "0.3.1"
 commons-codec "1.10"
 commons-io "2.5"
 commons-lang "2.6"
 commons-logging "1.1.3"
 jline "2.12.1"
 net.cgrand/parsley "0.9.3"
 net.cgrand/regex "1.1.0"
 net.cgrand/sjacket "0.1.1"
 org.apache.httpcomponents/httpclient "4.5"
 org.apache.httpcomponents/httpcore "4.4.1"
 org.apache.httpcomponents/httpmime "4.5"
 org.apache.maven.wagon/wagon-http "2.10"
 org.apache.maven.wagon/wagon-http-shared "2.10"
 org.apache.maven.wagon/wagon-provider-api "2.2"
 org.apache.maven/maven-aether-provider "3.0.4"
 org.apache.maven/maven-model "3.0.4"
 org.apache.maven/maven-model-builder "3.0.4"
 org.apache.maven/maven-repository-metadata "3.0.4"
 org.clojure/data.xml "0.0.8"
 org.clojure/tools.cli "0.3.1"
 org.clojure/tools.macro "0.1.5"
 org.clojure/tools.nrepl "0.2.12"
 org.codehaus.plexus/plexus-classworlds "2.4"
 org.codehaus.plexus/plexus-component-annotations "1.5.5"
 org.codehaus.plexus/plexus-interpolation "1.14"
 org.codehaus.plexus/plexus-utils "2.0.6"
 org.flatland/classlojure "0.7.1"
 org.jsoup/jsoup "1.7.2"
 org.sonatype.aether/aether-api "1.13.1"
 org.sonatype.aether/aether-connector-file "1.13.1"
 org.sonatype.aether/aether-connector-wagon "1.13.1"
 org.sonatype.aether/aether-impl "1.13.1"
 org.sonatype.aether/aether-spi "1.13.1"
 org.sonatype.aether/aether-util "1.13.1"
 org.sonatype.sisu/sisu-guice "3.0.3" :classifier "no_aop"
 org.sonatype.sisu/sisu-inject-bean "2.2.3"
 org.sonatype.sisu/sisu-inject-plexus "2.2.3"
 org.tcrawley/dynapath "0.2.5"
 pedantic "0.2.0"
 potemkin "0.4.1"
 quoin "0.1.2"
 reply "0.3.7"
 riddley "0.1.10"
 robert/hooke "1.3.0"
 scout "0.1.1"
 slingshot "0.12.2"
 stencil "0.5.0"
 tigris "0.1.1"
 trptcolin/versioneer "0.1.1"
 }
